repos:
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        additional_dependencies:
        - flake8-bandit
        - flake8-blind-except
        - flake8-bugbear
        - flake8-comprehensions
        - flake8-debugger
        - flake8-docstrings
        - flake8-string-format
        - flake8-builtins
        - flake8-quotes
        - pep8-naming
- repo: https://github.com/ambv/black
  rev: 21.6b0
  hooks:
    - id: black
- repo: local
  hooks:
    - id: pytest
      name: pytest
      entry: pytest
      language: system
      pass_filenames: false
      always_run: true
